version: "3"
services:
  service_nginx:
    container_name: nginx
    restart: always
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8081:8081"
      - "8084:8084"
      - "8085:8085"
      - "8086:8086"
      - "8087:8087"
    volumes:
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/ssl:/etc/nginx/ssl
      - ./log/nginx:/var/log/nginx
      - ./www:/app
    links:
      - service_node
    networks:
      lnmp-network:
        aliases:
          - service_nginx
    depends_on:
      - service_php56
      - service_php70
      - service_php72
      - service_node
    privileged: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  service_node:
    container_name: node
    image: cjun/web:staging-latest
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: pm2-docker start pm2.json
    env_file:
      - node.env
    networks:
      lnmp-network:
        aliases:
          - service_node
    privileged: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  service_php72:
    image: php72
    container_name: php72
    restart: always
    expose:
      - "9000"
    volumes:
      - ./www/:/app:rw
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php/fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php:/var/log/dnmp/:rw
    networks:
      lnmp-network:
        aliases:
          - service_php72
    privileged: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  service_php70:
    image: php70
    container_name: php70
    restart: always
    expose:
      - "9000"
    volumes:
      - ./www/:/app:rw
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php/fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php:/var/log/dnmp/:rw
    networks:
      lnmp-network:
        aliases:
          - service_php70
    privileged: true

  service_php56:
    image: php56
    container_name: php56
    restart: always
    expose:
      - "9000"
    volumes:
      - ./www/:/app:rw
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php/fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php:/var/log/dnmp/:rw
    networks:
      lnmp-network:
        aliases:
          - service_php56
    privileged: true

  service_mysql:
    container_name: mysql
    restart: always
    image: mysql:5.6
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./data/mysql:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
    networks:
      lnmp-network:
        aliases:
          - service_mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    privileged: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
networks:
  lnmp-network:
