version: "3"
services:
  service_nginx:
    container_name: nginx
    restart: always
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - /e/test/laravel:/www
      - /e/www/docker/nginx/confd:/etc/nginx/conf.d
    privileged: true
    networks:
      test:
        aliases:
          - service_nginx
    links:
      - service_php73
    depends_on:
      - service_php73
  service_php73:
    container_name: php73
    build: ./php
    # image: php:7.3-fpm
    restart: always
    expose:
      - "9000"
    volumes:
      - /e/test/laravel:/www
      - /e/www/docker/php/php.ini:/usr/local/etc/php/php.ini
      - /e/www/docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - service_mysql
    networks:
      test:
        aliases:
          - service_php73
    privileged: true
  service_mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    expose: 
      - 3306
    ports:
      - 3306:3306
    volumes:
      - /e/www/docker/mysql/my.cnf:/etc/mysql/my.cnf
      - /e/www/docker/mysql/data:/var/lib/mysql
      - /e/www/docker/mysql/log:/var/log/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    command: --default-authentication-plugin=mysql_native_password
    networks: 
      test:
        aliases:
          - service_mysql
    privileged: true
  # service_mysql:
  #   container_name: mysql
  #   image: mysql:5
  #   restart: always
  #   expose: 
  #     - 3306
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - /e/www/docker/mysql/my.cnf:/etc/mysql/my.cnf
  #     - /e/www/docker/mysql/data:/var/lib/mysql
  #     - /e/www/docker/mysql/log:/var/log/mysql
  #   environment:
  #     - MYSQL_USER=root
  #     - MYSQL_PASSWORD=123456
  #     - MYSQL_ROOT_PASSWORD=123456
  #   command: --default-authentication-plugin=mysql_native_password
  #   networks: 
  #     test:
  #       aliases:
  #         - service_mysql
  #   privileged: true
  # service_php56:
  #   container_name: php56
  #   image: php:5.6-fpm
  #   restart: always
  #   expose:
  #     - "9000"
  #   volumes:
  #     - "/c/Users/admin/code/v1.firmoo:/www"
  #   networks:
  #     test:
  #       aliases:
  #         - service_php56
  #   privileged: true
networks: 
  test: